### ISSUE TITLE
mavenize the project

### ISSUE THREAD

**Issue by yogeshrao** [kyrill007/loosejar#6]
Hi,

I wanted loosed jar as part of my automated build (based on maven) and realised its not part of mvn repo. I have gone ahead and mavenized the project in my repo, sending u a PR for the same.

BTW thank you for the project.

Regards,
-Yogesh

**Comment by yogeshrao** [comment]
How does releasing the project on maven central sound to you? If yes i can hep fix that..

**Comment by kyrill007** [comment]
I absolutely love this idea! Thanks for helping with that.

**Comment by yogeshrao** [comment]
Before I proceed on this. Since maven support is now available as part of loosejar

1. can we remove ant now?
2. remove lib directory?
3. remove .idea directory?

**Comment by kyrill007** [comment]
Sure, I am ok with completely Mavenizing it. :)

**Comment by yogeshrao** [comment]
What license is the project released under ? Is it [Apache License version 2 ](http://www.apache.org/licenses/LICENSE-2.0.txt)?

**Comment by kyrill007** [comment]
Yes! Feel free to add the license text to the project. And again, thank you for your help!

**Comment by yogeshrao** [comment]
you are welcome.. having it part of central repo also helps me :) 

btw the group id of the project would change to com.googlecode.loosejar and the artifact id would be loosejar,

**Comment by yogeshrao** [comment]
just curious would you be able to follow couple of steps mentioned here http://stackoverflow.com/questions/28846802/how-to-manually-publish-jar-to-maven-central, seems to me it would be better if the author did it.

 I have made all the other changes and will raise a pull request for the same.

**Comment by kyrill007** [comment]
I'll get to it this week, Yogesh.

Thanks again, man!

-K.

**Comment by yogeshrao** [comment]
Thanks Kyrill! 

please let me know once the jar is available on maven central.

**Comment by kyrill007** [comment]
It's just been released, Yogesh. Thanks for your help!

**Comment by yogeshrao** [comment]
Wow thats great news!!! Thank you ...
