### ISSUE TITLE
CSV based output support

### ISSUE THREAD

**Issue by yogeshrao** [kyrill007/loosejar#8]
Hi,

Apart from the summary style whic loose jar currently supports i was wondering if the project could support a CSV format which can be analyzed easily. Providing this option should be fairly simple.

Let me know if it would add any value ?

**Comment by kyrill007** [comment]
Hi Yogesh, I think it would because it would allow machine based parsing. If you're willing to contribute a patch, I will definitely merge it!

**Comment by yogeshrao** [comment]
Sure, let me try and have something for this weekend as i too need that piece of code :)

**Comment by yogeshrao** [comment]
Hi,

Generated pull request #9

**Comment by yogeshrao** [comment]
merged into master.
